name: home_robot3
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision>=0.15.2
  - pytorch-cuda=11.8
  - numpy>=1.25.2
  - accelerate
  - pip
  - pip:
    - byol_pytorch==0.5.7
    - einops==0.7.0
    - hydra-core==1.3.2
    - matplotlib==3.5.1
    - numpy_quaternion==2022.4.2
    - omegaconf==2.3.0
    - open3d==0.16.0
    - Pillow==9.5.0
    - pyliblzfse==0.4.1
    - tqdm==4.65.0
    - timm==0.9.2
    - wandb==0.15.8
    - scipy==1.10.0
    - vit_pytorch==1.6.4
    - opencv-python
    - opencv-contrib-python
    - decord==0.6.0
    - blosc==1.11.1
    - pyzmq==26.0.3
    - gdown==5.2.0
    - diffusers==0.11.1
    - openai==1.47.0
    - gradio
